# Generated by Django 5.0.6 on 2024-06-26 10:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("biodata", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contactform",
        ),
    ]
